name: pre-commit
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  pre-commit:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.1
